# site name
prefixName: 猪皮皮皮の
siteName: 博客
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /avatar/2.jpg
url: https://wudalei.github.io
description: 欢迎你来到这个神秘的博客，嘿嘿嘿!
cdn: https://cdn.jsdelivr.net/gh/wudalei/static@1.3
pjax: 1
# 1开启
mathjax: 0

notice: 认认真真的写博客，记录自己的生活和总结学到的技术，过好每一天 ︿(￣︶￣)︿
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  技术分享: { path: javascript:;, fa: fa-archive faa-shake, submenus: { 
    总结: {path: /categories/技术/, fa: fa-code }, 
    小笔记: {path: /categories/小笔记/, fa: fa-file-text-o }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    归档: {path: /archives,fa: fa-archive }
    # 转载: {path: /categories/转载/, fa: fa-book }
  } }
  宅power!: { path: javascript:;, fa: fa-thumbs-up faa-vertical, submenus: { 
    图: {path: /imgs/, fa: fa-photo },
    书: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌: {path: /music/, fa: fa-headphones },
    # 资源: {path: /categories/资源/, fa: fa-cloud-download }, 
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  # 友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: javascript:;, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    # Lab: {path: /lab/, fa: fa-cogs },
  } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/wudalei/static@1.1/bgImg/bg1.jpg
  - https://cdn.jsdelivr.net/gh/wudalei/static@1.1/bgImg/bg2.jpg
  - https://cdn.jsdelivr.net/gh/wudalei/static@1.1/bgImg/bg3.jpg
  - https://cdn.jsdelivr.net/gh/wudalei/static@1.1/bgImg/bg4.jpg
  - https://cdn.jsdelivr.net/gh/wudalei/static@1.1/bgImg/bg5.jpg
  - https://cdn.jsdelivr.net/gh/wudalei/static@1.1/bgImg/bg6.jpg
  - https://cdn.jsdelivr.net/gh/wudalei/static@1.1/bgImg/bg7.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /categories/技术/, title: 技术, desc: 博主学习到的知识, img: /image/8.jpg}
  - {url: /tags/图集/, title: 图集, desc: 博主的正经收藏, img: /image/5.jpg}
  - {url: /tags/图集/, title: 资源 ,desc: 博主的神秘资源, img: /image/11.jpg}



# your site build time or founded date
siteBuildingTime: 07/17/2018

#social  url, img PC端配置
social:
 github: {url: https://github.com/wudalei, img: /icon/github.svg}
 wechat: {url: /#, qrcode: /avatar/avator.jpg, img: /icon/wx.svg}

#social  url, img 移动端配置
msocial:
 github: {url:https://github.com/wudalei, fa: fa-github, color: 333}
 qq: {url: https://wpa.qq.com/msgrd?v=3&uin=1093192381&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.baidu.com
  alipay:  /avatar/avator.jpg
  wechat:  /avatar/avator.jpg
  wechatSQ:  /avatar/avator.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

